### ISSUE TITLE
Memory leak in MEMPTR

### ISSUE THREAD

**Issue by kaurvali** [gabsoftware/Progress-ABL-4GL-Regex#2]
Hi! 

Tried using it for regex and it work well, but over sustained longer load, it appears that there is a drastic memory leak on some MEMPTR in _regex.i_. Probably something related to pt_pcre or pt_pcre_extra.

**Comment by lievendf** [comment]
I've also noticed the same, it appears that no calls to
```
pcre2_match_data_free(match_data);
pcre2_code_free(re);
```
are being done.
I've tried calling these with the memptrs that were returned earlier as input, but that seems to fail.
Anyone had any success on this?

**Comment by gabsoftware** [comment]
> I've also noticed the same, it appears that no calls to
> 
> ```
> pcre2_match_data_free(match_data);
> pcre2_code_free(re);
> ```
> 
> are being done. I've tried calling these with the memptrs that were returned earlier as input, but that seems to fail. Anyone had any success on this?

These functions are PCRE2 functions. This code uses the PCRE1 library.

The memory leak should be fixed since commit c36971f4626746eaa3ce2af10c8c6f8c277405e4

First I forgot to call pcre_free_study(), so I added that function and called it where relevant.
Second, I used SET-SIZE() = 0 on the pcre MEMPTR. It appears that the pcre_free function is just a pointer to another function provided by the user, that is why calling it was making the program crash, because it points to a non-existent function. So SET-SIZE should do the job.

Let me know if that works better for you now.
